name: continious integration on features
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: init
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v1
        with:
          java-version: '12'
      - name: debug
        run: env
      - name: cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - id: verify
        name: is artifact eligable for deployment
        uses: navikt/bidrag-actions/release-verify-auto-deploy@feature-verify-auto-deploy
        with:
          changelog-file: README.md
          release-version: ingen
      - name: release candidate
        run: echo "release candidate - ${{ jobs.build.steps.verif.is-release-candidate }}"
      - name: verify that no dependencies are of type SNAPSHOT
        uses: navikt/bidrag-actions/verify-mvn-dependencies@master
        if: find_output.is-release-candidate
      - name: build & test with maven
        run: mvn -B install
        if: jobs.build.steps.verify.is-release-candidate
