name: continious integration on features
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: init
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v1
        with:
          java-version: '12'
      - name: debug
        run: env
      - name: cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: verify that no dependencies are of type SNAPSHOT
        uses: navikt/bidrag-actions/verify-mvn-dependencies@feature-io
      - id: prepare
        name: prepare release of maven package
        uses: navikt/bidrag-actions/release-prepare-for-mvn@feature-io
      - id: verify
        name: is artifact eligable for deployment
        uses: navikt/bidrag-actions/release-verify-auto-deploy@feature-io
        with:
          changelog-file: README.md
      - name: build & test with maven
        run: mvn -B install
        if: steps.verify.is-release-candidate
