name: continious integration on features
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      ARTIFACT: 'jactor-persistence'
      IMAGE: 'maven:3.6.2-jdk-13'
      M2_REPO: '.m2/repository'

    steps:
      - name: init
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: debug
        run: env
      - name: cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: verify that no dependencies is of type SNAPSHOT
        run: |
          docker run --rm --name "$ARTIFACT-dependencies" \
            -v "$HOME/.m2":/root/.m2 \
            -v "$PWD":/usr/src/maven \
            -w /usr/src/maven "$IMAGE" mvn -B dependency:tree | tee dependency.tree
          export COUNT="$(tail -n +5 deps | grep -v :test | grep -v $ARTIFACT | grep -c SNAPSHOT)"
          if [ $COUNT -eq 1 ]
            then
              >&2 echo ERROR: Found a SNAPSHOT dependency in "$ARTFIFACT"
              exit 1;
          elif [ $COUNT -gt 0 ]
            then
              >&2 echo ERROR: Found $COUNT SNAPSHOT dependencies in "$ARTFIFACT"
              exit 1;
          fi
      - name: build & test with maven
        run: |
          docker run --rm --name "$ARTIFACT-build" \
            -v "$HOME/.m2":/root/.m2 \
            -v "$PWD":/usr/src/maven \
            -w /usr/src/maven "$IMAGE" mvn -B install
