name: continious integration on features
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: init
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v1
        with:
          java-version: '12'
      - name: debug
        run: env
      - name: cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: verify that no dependencies are of type SNAPSHOT
        uses: navikt/bidrag-actions/verify-mvn-dependencies@master
      - name: build & test with maven
        run: mvn -B install
      - name: prepare-release
        uses: navikt/bidrag-actions/prepare-release-mvn-pkg@feature-prepare
      - run: echo "${{ steps.prepare_release.outputs.commit-sha }}"
