name: maven deploy
on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: '13'
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: navikt/bidrag-actions/maven-verify-dependencies@v1.0.2-maven
      - run: mvn -B install -e
      - uses: navikt/bidrag-actions/release-prepare-mvn-pkg@feature-outputs
        id: prepare
        if: github.ref == 'refs/heads/master'
      - uses: navikt/bidrag-actions/release-verify-auto-deploy@feature-outputs
        id: verify
        if: github.ref == 'refs/heads/master'
        with:
          changelog_file: README.md
          release_version: ${{ steps.prepare.release_version }}
      - uses: navikt/bidrag-actions/release-mvn-pkg@feature-outputs
        if: github.ref == 'refs/heads/master'
        with:
          new_snapshot_version: ${{ steps.prepare.new_snapshot_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: navikt/bidrag-actions/git-tag-n-commit-mvn-deploy@feature-outputs
        if: github.ref == 'refs/heads/master'
        with:
          commit_message: Bumped to new SNAPSHOT version after release of version  ${{ steps.prepare.release_version }}
          tag_message: Released new version ${{ steps.prepare.release_version }}
          pattern: pom.xml
          is_release_cancidate: ${{ steps.verify.is_release_candidate }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
