name: test build on pull request
on: [pull_request]

jobs:
  build-pull-request:
    name: Test pull-request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: env
      - run: mvn -B install -e
